name = "localhost-1313"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=localhost%3A1313"
HMAC_KEY = "7b1b8b0d3bdbd627680de9cc39e2567582e015ea790b26afb8cefdf92725728a"
COOKIE_NAME = "ju7"
PLAY_PATH = "try-now"
BUTTON_ID = "pdfda88d983bc5fad4f052a4ae426b8bf"
GATE_SALT = "68b928f9acd187fd"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "0v4s"
CTA_SELECTOR = ".play-button"
